name: Scheduled UI Tests - DEV Environment

on:
  schedule:
    # Runs every 2 hours during work hours (Mon-Fri, 9 AM - 5 PM UTC)
    - cron: "0 15 * * *" 
  workflow_dispatch: # Allows manual trigger
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - critical
          - regression

env:
  ENVIRONMENT: dev
  BASE_URL: https://automationexercise.com

jobs:
  test:
    name: Run Playwright Tests - DEV
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'LTS'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run all tests
        if: ${{ github.event.inputs.test_suite == 'all' || github.event.inputs.test_suite == '' }}
        run: npx playwright test
        env:
          CI: true

      - name: Run critical tests only
        if: ${{ github.event.inputs.test_suite == 'critical' }}
        run: npx playwright test tests/critical
        env:
          CI: true

      - name: Run regression tests only
        if: ${{ github.event.inputs.test_suite == 'regression' }}
        run: npx playwright test tests/regression
        env:
          CI: true

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-dev-${{ github.run_number }}
          path: playwright-report/
          retention-days: 7

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-dev-${{ github.run_number }}
          path: test-results/
          retention-days: 7

      - name: Comment Test Results on PR
        if: github.event_name == 'pull_request' && always()
        uses: daun/playwright-report-comment@v3
        with:
          report-path: playwright-report

  notify:
    name: Notify Test Results
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Send notification
        run: |
          echo "Tests completed with status: ${{ needs.test.result }}"
          echo "Environment: DEV"
          echo "Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
